spring:
  application:
    name: pass-batch
  datasource:
    url: jdbc:mysql://127.0.0.1:9999/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:                        # Spring Boot 2 부터 Default DBCP 는 hikariCP 입니다.
      maximum-pool-size: 20        # pool 에 보관 가능한 최대 connection 수

  batch:
    jdbc:
      # Batch에 사용되는 SQL 초기화 스크립트를 수행합니다. 임베디드인 경우엔 기본으로 실행하는데,
      # always 를 설정하면 임베디드 타입처럼 항상 활성화 시킬 수 있습니다.
      # 초기 수행 이후, 꺼두어도 됩니다.
      initialize-schema: always